# Generated by Django 6.0.6 on 2026-06-18 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('description_activite', models.TextField(blank=True)),
                ('est_approuve', models.BooleanField(default=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_vendeur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
