# Generated by Django 5.2.8 on 2026-06-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_profilvendeur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilvendeur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
