# Generated by Django 5.2.8 on 2026-06-21 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_profilvendeur_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilvendeur',
            name='description_activite',
        ),
        migrations.AddField(
            model_name='profilvendeur',
            name='adresse',
            field=models.TextField(default='Adresse à renseigner'),
        ),
        migrations.AlterField(
            model_name='profilvendeur',
            name='nom_boutique',
            field=models.CharField(default='Ma boutique', max_length=200),
        ),
        migrations.AlterField(
            model_name='profilvendeur',
            name='telephone',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilvendeur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilvendeur', to=settings.AUTH_USER_MODEL),
        ),
    ]
