# Generated by Django 6.0.6 on 2026-06-18 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stock',
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='comptes.profilvendeur'),
        ),
    ]
