# Generated by Django 5.2.8 on 2026-06-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_remove_produit_slug_remove_produit_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse complète de livraison')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=10)),
                ('resume_produits', models.TextField(blank=True, verbose_name='Articles commandés')),
            ],
        ),
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
