# Generated by Django 5.2.8 on 2026-06-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_alter_categorie_id_alter_commande_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date_commande',
            new_name='date_creation',
        ),
    ]
