# Generated by Django 5.2.8 on 2026-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_rename_date_commande_commande_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de livraison'), ('livre', 'Livré')], default='en_attente', max_length=20),
        ),
    ]
